### ISSUE TITLE
What's the reason using DDPM instead of DDIM?

### ISSUE THREAD

**Issue by jaehoone** [lijiaman/egoego_release#1]
Thank you for sharing an interesting work.

Is there any reason that the EgoEgo uses DDPM as a scheduler?

From my knowledge, some schedulers, such as DDIM and DPMSolver, can accelerate the sampling process.

**Comment by lijiaman** [comment]
Hi, we didn't try DDIM since we were not aiming for speed in this project. DDIM or DPMSolver can be used here, but I'm not sure if they would introduce some artifacts like jitters.
