### ISSUE TITLE
Running test_egoego_pipeline.sh over EPIC Kitchens

### ISSUE THREAD

**Issue by edessa** [lijiaman/egoego_release#2]
Hello,

I am trying to extract full body pose information from the EPIC Kitchens dataset by running the script you all have provided. I must beforehand extract head pose data from DROID-SLAM and optical flow from RAFT. I have had trouble producing the exact optical flow features your pipeline requires, as the RAFT repository does not provide models that produce the optical flow dimensions (512,) your pipeline requires. Could you please point to which of the models on the RAFT repository you ended up using, and which variable within the model architectures you use to retrieve the features? Thank you ahead of time!

**Comment by L-Scofano** [comment]
Hello, I'm currently facing the same problem with RAFT, which model should be used?
Thank you in advance!

**Comment by lijiaman** [comment]
Hi, 
We used ResNet to extract the optical flow features. You can find the ResNet extractor here https://github.com/lijiaman/egoego_release/blob/main/egoego/model/resnet.py#L25. For using RAFT, I believe we used a default one, either network should work.
