### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed_amass_same_shape_seq/Eyes_Japan_Dataset/aita/accident-08-damage rightfoot-aita_poses_719_frames_30_fps.npz'

### ISSUE THREAD

**Issue by gwbao** [lijiaman/egoego_release#4]
execute command：python extract_amass_motion_for_ares.py
The following error occurred：
  Traceback (most recent call last):
    File "extract_amass_motion_for_ares.py", line 61, in <module>
      read_motion_from_habitat(amass_data_folder, habitat_folder, extract_index_pkl_path)
    File "extract_amass_motion_for_ares.py", line 37, in read_motion_from_habitat
      ori_npz_data = np.load(ori_data_path, allow_pickle=True) 
    File "/root/miniconda3/envs/egoego_env/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
      fid = stack.enter_context(open(os_fspath(file), "rb"))
  FileNotFoundError: [Errno 2] No such file or directory: 'data/processed_amass_same_shape_seq/Eyes_Japan_Dataset/aita/accident-08-damage rightfoot-aita_poses_719_frames_30_fps.npz'

**Comment by unparalleled-soul** [comment]
Hello, I'm having the same problem. Please have you solved this problem? And how did you solve it? Thanks.
